### PR TITLE
Send existing flags to aoflagger

### PR DESCRIPTION
**Pull request by aroffringa**
These changes make it possible to ignore the pre-flagged data (edge channels, dc channel, first seconds). This is thought to be useful for removing some flagging bias seen on short baselines and/or near the edges. Bart found that these flags can be an issue for RTS EoR analyses.

This version also adds an option `-flag-strategy`, which takes an aoflagger `.rfis` file, which can be used to override the default 'mwa' strategy.

To correctly use these changes, a recent version of `aoflagger`: either today's (2019-12-12) aoflagger git version, which reports itself as version 2.14.2, or of course a future 2.15 distributed release.

### CODE REVIEW

**Comment by aroffringa** [comment]
@cjordan (if you're the right person to ask:) Not sure what kind of software-deployment is in place for Cotter, but would you like to do a check if this version still compiles and runs on most of your platforms before I merge?

**Comment by cjordan** [comment]
@aroffringa I will do some testing ASAP next week and report back.

**Comment by cjordan** [comment]
As promised, I did a little testing.  New aoflagger and cotter compile on my machine fine, and a look at a wsclean of a single EoR-0 observation suggests that there is no difference to be seen.  I can be more thorough in my comparison, just let me know, but maybe you should give me pointers on what to look for in the flags.

Unfortunately, the python 3 requirements mean that a little more work needs to be done for me to get this all working on Pawsey, but this is a day I always knew would come.

BTW @aroffringa, it looks like you've bumped the version in aoflagger, but there isn't an associated git tag.  Maybe you forgot to push it?  In any case, would you mind doing that, so the new version has increased visibility?

**Comment by aroffringa** [comment]
Thanks a lot! More testing is not necessary -- I did my own testing as well. I'll tag the new version.

**Pull request merged**
