### PR TITLE
Remove dependency on Boost signals

### LINKED ISSUE #2: Boost's signals library has been removed - can no longer compile cotter
Hey André,

[The changelog](https://www.boost.org/users/history/version_1_69_0.html) for the newest version of boost announces the signal library removal.  I'm not sure if the signals2 library is available in older versions of boost, or how much work it is to allow CMake to handle things, but your help would be appreciated!  Let me know if there's anything I can do.

### PR DESCRIPTION
**Pull request by aroffringa**
Boost no longer ships with signals, as it has been replaced with signals2.
Cotter actually does not require signals, so the dependency could be removed.
I probably sneaked in because it used to be a dependency for aoflagger, which
is recently changed to signals2 on trunk. Fixes #2.

### CODE REVIEW

**Comment by aroffringa** [comment]
@cjordan can you check whether this branch + trunk aoflagger solves #2 ?

**Comment by cjordan** [comment]
Thanks André, that works!

**Comment by aroffringa** [comment]
@cjordan You closed the merge request; did you intend to close the bug report instead (#2). The merge request needs to be merged before it has effect ;). I'll do that now.

**Comment by cjordan** [comment]
Sorry about that, but thanks again!

**Pull request merged**
